/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef file_dragger_CONSTANTS_H
#define file_dragger_CONSTANTS_H

#include "file_dragger_types.h"

namespace file_dragger {

class file_draggerConstants {
 public:
  file_draggerConstants();

};

extern const file_draggerConstants g_file_dragger_constants;

} // namespace

#endif
