/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "file_dragger_constants.h"

namespace file_dragger {

const file_draggerConstants g_file_dragger_constants;

file_draggerConstants::file_draggerConstants() {
}

} // namespace

